// <auto-generated />
namespace ComputerRepairDataAccesL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class enable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enable));
        
        string IMigrationMetadata.Id
        {
            get { return "202207061538057_enable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
